### ISSUE TITLE
Dataset about WDRef & lfw

### ISSUE THREAD

**Issue by AmazingWK** [KaenChan/ProbFace#1]
I see the descriptions about lbp_WDRef.mat, id_WDRef.mat and lbp_lfw.,mat in the README file, but they are not in the folder. So, could you please upload them or share me the way to download? It will help a lot. Thank you very much!!

**Comment by KaenChan** [comment]
This files are not used for this project. I've been modifying the readme. In addition, I don't have these files.

**Comment by AmazingWK** [comment]
ok, thanks for reply.
